dataset_reader:
  type: new_bm_rel
  tokenizer:
    type: word
    word_splitter: just_spaces_keep_newlines
  token_indexers:
    roberta:
      type: roberta
      model_name: roberta-base
      namespace: bpe
      padding_on_right: true
      padding_value: 1
      max_len: 512
  mongo_host: "nova"
  image_dir: /home/joberant/nlp_fall_2021/shlomotannor/newscaptioning/data/nytimes/images_processed
  lazy: true
  use_caption_names: false
  use_objects: true
  articles_num: -1
  use_first: false
  sort_BM: true
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: roberta
  directory_path: ./expt/vocabulary
model:
  type: BMRelModel
  criterion:
    type: adaptive_loss
    padding_idx: 1
  use_context: true
  evaluate_mode: false
  sampling_topk: 1
  vocab_size: 50265
  hidden_size: 1024
  attention_dim: 1024
  namespace: bpe
  index: roberta
  weigh_bert: true
  padding_value: 0

iterator:
  type: bucket
  sorting_keys:
    - - context
      - num_tokens
    - - caption
      - num_tokens
  batch_size: 16
  max_instances_in_memory: 8192
  biggest_batch_first: false
  instances_per_epoch: 65536
  maximum_samples_per_batch: [ "num_tokens", 16384 ]
validation_iterator:
  type: bucket
  sorting_keys:
    - - context
      - num_tokens
    - - caption
      - num_tokens
  batch_size: 16
  max_instances_in_memory: 8192
  maximum_samples_per_batch: [ "num_tokens", 16384 ]
  biggest_batch_first: false
trainer:
  type: callback_apex
  apex_opt_level: O2
  keep_batchnorm_fp32: true
  optimizer:
    type: bert_adam
    lr: 0.01
    warmup: 0.0
    t_total: 437600 # Takees 43m to go through 4376 batches per epoch
    schedule: warmup_linear
    b1: 0.9
    b2: 0.98
    e: 0.000001
    weight_decay: 0.00001 # Worse choices: 0.01, 0.001, 0.000001
    max_grad_norm: 10000 # Worse choices: 1.0
    parameter_groups:
      - - - ^decoder.embedder
        - { }
      - - - ^decoder.layers.0
        - { }
      - - - ^decoder.layers.1
        - { }
      - - - ^decoder.layers.2
        - { }
      - - - ^decoder.layers.3
        - { }
      - - - ^decoder.adaptive_softmax
        - { }
  no_grad:
    - ^resnet
    - ^roberta
  num_epochs: 100
  shuffle: true
  cuda_device: 0
  callbacks:
    - type: checkpoint
      checkpointer:
        num_serialized_models_to_keep: 10
    - type: track_metrics
      patience: 30
    - type: validate
    - type: log_to_tensorboard
      summary_interval: 512
      should_log_parameter_statistics: false
      log_batch_size_period: 1024
