dataset_reader:
  type: BMReader
  tokenizer:
    type: word
    word_splitter: just_spaces_keep_newlines
  token_indexers:
    roberta:
      type: roberta
      model_name: roberta-base
      namespace: bpe
      padding_on_right: true
      padding_value: 1
      max_len: 512
  mongo_host: "nova"
  image_dir: data/nytimes/images_processed
  lazy: true
  use_caption_names: false
  use_objects: true
  articles_num: 5
train_data_path: train
validation_data_path: valid
test_data_path: test
trainer:
  "optimizer": "adam"
  "num_epochs": 1